name: Local Agent
version: 1.0.0
schema: v1

models:
  - name: GPT-5
    provider: openai
    model: gpt-5

  - name: GPT-4o
    provider: openai
    model: gpt-4o

  - name: GPT-4o-mini
    provider: openai
    model: gpt-4o-mini

  - name: GPT-4.1
    provider: openai
    model: gpt-4.1

  - name: GPT-4.1-mini
    provider: openai
    model: gpt-4.1-mini
